# SwiftLint configuration for SwiftUI Query (Swift 6)

# Paths to include and exclude
included:
  - Sources
  - Tests
  - Example

excluded:
  - Documentation
  - .build
  - .swiftpm
  - Package.swift
  - ${PWD}/Documentation

# Rule configuration
disabled_rules:
  - trailing_comma # Allow trailing commas in arrays/dictionaries
  - todo # Allow TODO comments during development

# Per-path rule customization
force_unwrapping:
  severity: warning

opt_in_rules:
  # Swift 6 and Modern Swift Best Practices
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

# Rule configuration
analyzer_rules:
  - unused_declaration
  - unused_import

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 800
  error: 1000

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level:
    warning: 3
    error: 4
  function_level:
    warning: 3
    error: 4

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 45
    error: 60
  excluded:
    - id
    - URL
    - url
    - i
    - j
    - k
    - x
    - y
    - z
    - _

large_tuple:
  warning: 3
  error: 4

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

attributes:
  always_on_same_line:
    - "@Environment"
    - "@EnvironmentObject"
    - "@ObservedObject"
    - "@StateObject"
    - "@State"
    - "@Binding"
  always_on_line_above:
    - "@ViewBuilder"

# Custom Rules
custom_rules:
  no_print_statements:
    name: "Print Statements"
    regex: '\bprint\s*\('
    message: "Use proper logging instead of print statements"
    severity: warning
    excluded:
      - Tests
      - Example

  force_https:
    name: "Force HTTPS"
    regex: 'http://'
    match_kinds:
      - string
    message: "Use HTTPS instead of HTTP"
    severity: warning


  observable_usage:
    name: "Observable Usage"
    regex: 'ObservableObject'
    message: "Consider using @Observable instead of ObservableObject for Swift 6"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "xcode"